# This program ask for your name and age and give you the length of your neme
print("what is your name? please enter.")
myname=input()
print("Your name is",myname,)
print("the length of your name is" ,(len(myname)),)
print("what is your age")
age=input()
print("your age is",age,)
print("after 1 year you are of", str(int(age)+1 ),"year old")
print ("press enetr to exit")
enter=input()
