input_test=input("enter food categories eaten in last 24 hrs:")
print('Tt is',"dairy"in input_test.lower(),'that',""+input_test+"",'contains "dairy"')
print('Tt is',"nuts"in input_test.lower(),'that',""+input_test+"",'contains "nuts"')
print('Tt is',"seafood"in input_test.lower(),'that',""+input_test+"",'contains "seafood"')
print('Tt is',"chocolate"in input_test.lower(),'that',""+input_test+"",'contains "chocolate"')
